---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /QBitVPN/qbittorrent/appdata:/config
      - /QBitVPN/downloads:/downloads #optional
    ports:
      - 8089:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /QBitVPN/sabnzbd/config:/config
      - /QBitVPN/incomplete/downloads:/incomplete-downloads #optional
      - /QBitVPN/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
